INGREDIENTS = [
  {"id":1,  "name":"Carmine",             "e_number":"E120",  "status":"haram",    "category":"colorant",
   "text":"""Carmine (E120) is a red food colorant derived from dried crushed cochineal insects (Dactylopius coccus). It is widely used in beverages, yogurt, candy, and ice cream. Because it is derived directly from insects, carmine is classified as haram in Islamic dietary law. Consumers must avoid E120, carminic acid, natural red 4, and cochineal extract — all synonyms for the same haram ingredient."""},
  {"id":2,  "name":"Gelatin",              "e_number":"E441",  "status":"mashbooh", "category":"thickener",
   "text":"""Gelatin (E441) is a protein from boiling animal bones and skin, most commonly from pigs or cows. Pork-derived gelatin is haram; beef gelatin is halal only if the animal was slaughtered according to Islamic rites. Gelatin is used in gummy candies, marshmallows, jellies, and capsules. Always verify source and look for halal-certified gelatin."""},
  {"id":3,  "name":"Citric Acid",          "e_number":"E330",  "status":"halal",    "category":"preservative",
   "text":"""Citric acid (E330) is produced commercially through fermentation of sugars by Aspergillus niger mold. It is used as a preservative and flavor enhancer in soft drinks, jams, and processed foods. Citric acid is considered halal as it is derived from plant-based fermentation with no animal components. It is one of the most widely accepted food additives in halal production."""},
  {"id":4,  "name":"Lard",                 "e_number":"N/A",   "status":"haram",    "category":"fat",
   "text":"""Lard is rendered fat from pigs, used in baking, frying, and as shortening in pastries and pie crusts. It is strictly haram in Islam because it is derived directly from pigs (swine). Lard may be listed as lard, pork fat, pig fat, or animal shortening on labels. Muslim consumers must verify halal certification or substitute with vegetable oils."""},
  {"id":5,  "name":"Lecithin",             "e_number":"E322",  "status":"mashbooh", "category":"emulsifier",
   "text":"""Lecithin (E322) is an emulsifier in chocolate, margarine, and baked goods. It can derive from soybeans (halal), sunflowers (halal), eggs, or animal sources (may be haram). Soy lecithin is most common and generally halal. When source is unspecified it is classified as mashbooh and requires halal certification verification."""},
  {"id":6,  "name":"Ascorbic Acid",        "e_number":"E300",  "status":"halal",    "category":"antioxidant",
   "text":"""Ascorbic acid (E300), also known as Vitamin C, is produced synthetically from glucose fermentation with no animal involvement. Used in juices, cereals, and meat products. Ascorbic acid is universally classified as halal. Also appears as sodium ascorbate (E301) and calcium ascorbate (E302), all halal."""},
  {"id":7,  "name":"Disodium Inosinate",   "e_number":"E631",  "status":"mashbooh", "category":"flavor_enhancer",
   "text":"""Disodium inosinate (E631) is a flavor enhancer used with MSG in snack foods and instant noodles. It can be produced from sardines (halal), pork meat (haram), or sugar fermentation (halal). Source determines halal status. Muslim consumers should seek halal certification since source is rarely disclosed on packaging."""},
  {"id":8,  "name":"Sodium Benzoate",      "e_number":"E211",  "status":"halal",    "category":"preservative",
   "text":"""Sodium benzoate (E211) is a preservative in acidic foods and soft drinks. Synthesized from benzoic acid and sodium hydroxide through chemical process with no animal materials. Sodium benzoate is halal by all major Islamic authorities. Note: reacts with Vitamin C to form benzene — a health concern separate from halal status."""},
  {"id":9,  "name":"L-Cysteine",           "e_number":"E920",  "status":"mashbooh", "category":"flour_improver",
   "text":"""L-Cysteine (E920) is a dough conditioner in commercial bread and croissants. Historically produced from duck feathers or hog hair; modern production uses synthetic fermentation. Duck-feather-derived L-Cysteine is mashbooh; synthetic forms are halal. McDonald's hamburger buns historically contained duck-feather L-Cysteine — a well-known halal concern."""},
  {"id":10, "name":"Tartrazine",           "e_number":"E102",  "status":"halal",    "category":"colorant",
   "text":"""Tartrazine (E102) is a synthetic lemon-yellow azo dye in soft drinks, candy, and cereals. Produced from coal tar derivatives through chemical synthesis with no animal components. Tartrazine is halal. It may cause hyperactivity in sensitive children — a health issue separate from halal status."""},
  {"id":11, "name":"Mono and Diglycerides", "e_number":"E471",  "status":"mashbooh", "category":"emulsifier",
   "text":"""Mono and diglycerides (E471) are emulsifiers in bread, margarine, and ice cream. Fatty acids may derive from plant oils (halal) or animal fats including pork (haram if from pig). Without source specification E471 is mashbooh. Halal-certified E471 must specify plant-based source such as palm, soy, or sunflower oil."""},
  {"id":12, "name":"Rennet",               "e_number":"N/A",   "status":"mashbooh", "category":"coagulant",
   "text":"""Rennet is an enzyme complex used in cheese production to coagulate milk. Animal rennet from calves is halal only if properly slaughtered; porcine rennet is haram. Microbial rennet and fermentation-produced chymosin are halal alternatives widely used in commercial cheese."""},
  {"id":13, "name":"Xanthan Gum",          "e_number":"E415",  "status":"halal",    "category":"thickener",
   "text":"""Xanthan gum (E415) is a polysaccharide produced by fermentation of sugars by Xanthomonas campestris bacteria. Used as thickener and stabilizer in sauces, dressings, and gluten-free baked goods. Xanthan gum is produced from plant-based sugars with no animal inputs and is universally halal."""},
  {"id":14, "name":"Calcium Propionate",   "e_number":"E282",  "status":"halal",    "category":"preservative",
   "text":"""Calcium propionate (E282) is a mold inhibitor in commercial bread and cakes. Synthesized by reacting propionic acid with calcium carbonate with no animal-derived ingredients. Calcium propionate is halal and approved by all major halal certification bodies."""},
  {"id":15, "name":"Sodium Nitrite",       "e_number":"E250",  "status":"halal",    "category":"preservative",
   "text":"""Sodium nitrite (E250) is a preservative in cured meats like sausages and hot dogs. Produced from sodium hydroxide through inorganic chemical synthesis with no animal ingredients. Sodium nitrite itself is halal; however the meats it preserves may be haram if from non-halal-slaughtered animals."""},
  {"id":16, "name":"Cochineal Extract",    "e_number":"E120",  "status":"haram",    "category":"colorant",
   "text":"""Cochineal extract (E120) is another name for carmine — the same red dye from crushed cochineal insects. Appears as cochineal, carmine, carminic acid, natural red 4, or E120 on labels. Since derived from insects it is haram. Recognizing all synonyms is critical when checking ingredient lists."""},
  {"id":17, "name":"Potassium Sorbate",    "e_number":"E202",  "status":"halal",    "category":"preservative",
   "text":"""Potassium sorbate (E202) inhibits mold and yeast in cheese, wine, dried fruits, and baked goods. Produced from sorbic acid and potassium hydroxide through chemical synthesis with no animal components. Potassium sorbate is halal and one of the most common preservatives in halal-certified food production."""},
  {"id":18, "name":"Polyglycerol Esters",  "e_number":"E475",  "status":"mashbooh", "category":"emulsifier",
   "text":"""Polyglycerol esters (E475) are emulsifiers in spreads, chocolate, and whipped cream. Fatty acids may derive from plant or porcine animal sources. Without source specification E475 is mashbooh. Plant-derived E475 from palm or soy is halal; animal-derived requires confirmation of halal slaughter."""},
  {"id":19, "name":"Annatto",              "e_number":"E160b", "status":"halal",    "category":"colorant",
   "text":"""Annatto (E160b) is a natural orange-yellow colorant extracted from seeds of the achiote tree (Bixa orellana). Used to color cheddar cheese, butter, and margarine. Being plant-derived from seed extract, annatto is halal with no animal-derived components."""},
  {"id":20, "name":"Carrageenan",          "e_number":"E407",  "status":"halal",    "category":"thickener",
   "text":"""Carrageenan (E407) is a polysaccharide extracted from red seaweed used as a thickener in plant-based milks, chocolate milk, and dairy-free ice cream. Entirely seaweed-derived and universally halal with no animal components."""},
]

BY_NAME   = {i["name"]:i for i in INGREDIENTS}
BY_STATUS = {"halal":[], "haram":[], "mashbooh":[]}
for i in INGREDIENTS: BY_STATUS[i["status"]].append(i)
# 20 total: 9 halal, 3 haram, 8 mashbooh